fun main() {
    println(ChatService.chatList)
    ChatService.createMessage(8 to 1,"hello")
    ChatService.createMessage(8 to 1,"hello")
    ChatService.createMessage(1 to 6,"hello")
    ChatService.createMessage(1 to 6,"hello")
    ChatService.createMessage(1 to 7,"hello")
    println(ChatService.chatList)
    ChatService.editMessage(8,0, "bye")
    println(ChatService.chatList)
    ChatService.deleteMessage(0)
    println(ChatService.chatList)
    ChatService.deleteChat(8 to 1)
    println(ChatService.chatList)
    println(ChatService.getChatsForUser(1))
    ChatService.getUnreadChatsCount(1)
    println(ChatService.getChatMessages(1 to 6, 0, 4))
    ChatService.getUnreadChatsCount(1)
}